/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tutoriasacademi.IGU;

/**
 *
 * @author jeffersonparedespretel
 */
public class PortalAlumno extends javax.swing.JFrame {

    /**
     * Creates new form PortalAlumno
     */
    public PortalAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosPersonaAlumno = new javax.swing.JFrame();
        jLabel237 = new javax.swing.JLabel();
        btnEditarAlumno = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtAreaDescripcionAlumno = new javax.swing.JTextArea();
        btnGuardarAlumno = new javax.swing.JButton();
        btnAtrasAlumno = new javax.swing.JButton();
        jDateChooser20 = new com.toedter.calendar.JDateChooser();
        jComboBox37 = new javax.swing.JComboBox<>();
        jLabel238 = new javax.swing.JLabel();
        txtCorreoAlumno = new javax.swing.JTextField();
        txtNacionalidadAlumno = new javax.swing.JTextField();
        txtClaveAlumno = new javax.swing.JTextField();
        jLabel240 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        txtNombreAlumo = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtUsuarioAlumno = new javax.swing.JTextField();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        TutoriasPasadas = new javax.swing.JFrame();
        jLabel236 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel235 = new javax.swing.JLabel();
        jButton76 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuItemDatosAlum = new javax.swing.JMenuItem();
        jMenuItemTutoriasPasa = new javax.swing.JMenuItem();
        jMenuTutorias = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel237.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel237.setText("Nombre:");

        btnEditarAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnEditarAlumno.setText("Editar");
        btnEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlumnoActionPerformed(evt);
            }
        });

        txtAreaDescripcionAlumno.setColumns(20);
        txtAreaDescripcionAlumno.setRows(5);
        jScrollPane20.setViewportView(txtAreaDescripcionAlumno);

        btnGuardarAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnGuardarAlumno.setText("Guardar");

        btnAtrasAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAtrasAlumno.setText("Atras");

        jDateChooser20.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jComboBox37.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Indeterminado" }));

        jLabel238.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel238.setText("Fecha de Nacimiento:");

        txtCorreoAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtNacionalidadAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtClaveAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel240.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel240.setText("Usuario");

        jLabel244.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel244.setText("Clave:");

        jLabel247.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel247.setText("Apellido:");

        jLabel248.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel248.setText("Datos Personales del Alumno:");

        jLabel249.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel249.setText("Genero:");

        jLabel250.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel250.setText("Nacionalidad:");

        txtNombreAlumo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtApellidoAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtApellidoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoAlumnoActionPerformed(evt);
            }
        });

        txtUsuarioAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel251.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel251.setText("Correo Electronico:");

        jLabel252.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel252.setText("Descripcion:");

        javax.swing.GroupLayout DatosPersonaAlumnoLayout = new javax.swing.GroupLayout(DatosPersonaAlumno.getContentPane());
        DatosPersonaAlumno.getContentPane().setLayout(DatosPersonaAlumnoLayout);
        DatosPersonaAlumnoLayout.setHorizontalGroup(
            DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel248)
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel247)
                            .addComponent(jLabel251)
                            .addComponent(jLabel237)
                            .addComponent(jLabel238)
                            .addComponent(jLabel250)
                            .addComponent(jLabel252))
                        .addGap(18, 18, 18)
                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonaAlumnoLayout.createSequentialGroup()
                                    .addComponent(txtNacionalidadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(167, 167, 167))
                                .addComponent(jDateChooser20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombreAlumo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(163, 163, 163)
                                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel244)
                                            .addComponent(jLabel240)))
                                    .addComponent(jLabel249))
                                .addGap(11, 11, 11)
                                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuarioAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtClaveAlumno)
                                    .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonaAlumnoLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnEditarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarAlumno)
                                .addGap(84, 84, 84)
                                .addComponent(btnAtrasAlumno)
                                .addGap(144, 144, 144))
                            .addComponent(jScrollPane20))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        DatosPersonaAlumnoLayout.setVerticalGroup(
            DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel248, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel237)
                    .addComponent(txtNombreAlumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel240)
                    .addComponent(txtUsuarioAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel247, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel244)
                    .addComponent(txtClaveAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel251)
                    .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel249)
                    .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel250)
                    .addComponent(txtNacionalidadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel238)
                        .addGap(24, 24, 24))
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addComponent(jDateChooser20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel252)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarAlumno)
                    .addComponent(btnGuardarAlumno)
                    .addComponent(btnAtrasAlumno))
                .addGap(56, 56, 56))
        );

        jLabel236.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel236.setText("En este apartado podras revisar toda la infromacon de las tutorias en las que participaste ");

        jLabel239.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel239.setText("Tutorias Pasadas del Alumno:");

        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane19.setViewportView(jTable19);

        javax.swing.GroupLayout TutoriasPasadasLayout = new javax.swing.GroupLayout(TutoriasPasadas.getContentPane());
        TutoriasPasadas.getContentPane().setLayout(TutoriasPasadasLayout);
        TutoriasPasadasLayout.setHorizontalGroup(
            TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TutoriasPasadasLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel236)
                .addGap(19, 19, 19))
            .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                .addGroup(TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel239))
                    .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TutoriasPasadasLayout.setVerticalGroup(
            TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel239)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel236)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel235.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel235.setText("Bienvenido Estudiante");

        jButton76.setText("Salir");

        jDesktopPane1.setLayer(jLabel235, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton76, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel235, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton76)
                .addGap(15, 15, 15))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel235, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton76)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenuPerfil.setText("Perfil");

        jMenuItemDatosAlum.setText("Datos Personales");
        jMenuPerfil.add(jMenuItemDatosAlum);

        jMenuItemTutoriasPasa.setText("Tutorias Pasadas");
        jMenuItemTutoriasPasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTutoriasPasaActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuItemTutoriasPasa);

        jMenuBar1.add(jMenuPerfil);

        jMenuTutorias.setText("Tutorias");

        jMenuItem3.setText("Pedir Tutorias");
        jMenuTutorias.add(jMenuItem3);

        jMenuItem4.setText("Tutorias");
        jMenuTutorias.add(jMenuItem4);

        jMenuBar1.add(jMenuTutorias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarAlumnoActionPerformed

    private void txtApellidoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoAlumnoActionPerformed

    private void jMenuItemTutoriasPasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTutoriasPasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTutoriasPasaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DatosPersonaAlumno;
    private javax.swing.JFrame TutoriasPasadas;
    private javax.swing.JButton btnAtrasAlumno;
    private javax.swing.JButton btnEditarAlumno;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton jButton76;
    private javax.swing.JComboBox<String> jComboBox37;
    private com.toedter.calendar.JDateChooser jDateChooser20;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemDatosAlum;
    private javax.swing.JMenuItem jMenuItemTutoriasPasa;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenu jMenuTutorias;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JTable jTable19;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextArea txtAreaDescripcionAlumno;
    private javax.swing.JTextField txtClaveAlumno;
    private javax.swing.JTextField txtCorreoAlumno;
    private javax.swing.JTextField txtNacionalidadAlumno;
    private javax.swing.JTextField txtNombreAlumo;
    private javax.swing.JTextField txtUsuarioAlumno;
    // End of variables declaration//GEN-END:variables
}
